packages:
  - packages/*
catalog:
  '@antfu/eslint-config': ^4.1.1
  '@eslint/config-array': ^0.19.2
  '@iconify-json/carbon': ^1.2.6
  '@iconify-json/catppuccin': ^1.2.8
  '@iconify-json/logos': ^1.2.4
  '@iconify-json/ph': ^1.2.2
  '@iconify-json/ri': ^1.2.5
  '@iconify-json/simple-icons': ^1.2.23
  '@nuxt/eslint': ^1.0.0
  '@pnpm/list': ^1000.0.6
  '@pnpm/types': ^1000.1.1
  '@shikijs/langs-precompiled': ^2.2.0
  '@shikijs/transformers': ^2.2.0
  '@types/connect': ^3.4.38
  '@types/d3': ^7.4.3
  '@types/d3-hierarchy': ^3.1.7
  '@types/ws': ^8.5.14
  '@typescript-eslint/utils': ^8.22.0
  '@unocss/eslint-config': ^65.4.3
  '@unocss/nuxt': ^65.4.3
  '@vueuse/nuxt': ^12.5.0
  birpc: ^2.0.19
  bumpp: ^10.0.1
  bundle-require: ^5.1.0
  cac: ^6.7.14
  chokidar: ^4.0.3
  d3: ^7.9.0
  d3-hierarchy: ^3.1.2
  d3-shape: ^3.2.0
  debug: ^4.4.0
  esbuild: ^0.24.2
  eslint: ^9.19.0
  fast-glob: ^3.3.3
  find-up: ^7.0.0
  flatted: ^3.3.2
  floating-vue: ^5.2.2
  fuse.js: ^7.1.0
  get-port-please: ^3.1.2
  h3: ^1.14.0
  launch-editor: ^2.9.1
  lint-staged: ^15.4.3
  mlly: ^1.7.4
  mrmime: ^2.0.0
  nitropack: 2.8.1
  nuxt: ^3.15.4
  nuxt-eslint-auto-explicit-import: ^0.1.1
  open: ^10.1.0
  package-manager-detector: ^0.2.9
  pathe: ^2.0.2
  picocolors: ^1.1.1
  pkg-types: ^1.3.1
  shiki: ^2.2.0
  simple-git-hooks: ^2.11.1
  structured-clone-es: ^1.0.0
  tinyexec: ^0.3.2
  typescript: ^5.7.3
  unbuild: ^3.3.1
  vite-hot-client: ^2.0.4
  vitest: ^3.0.4
  vue-tsc: ^2.2.0
  ws: ^8.18.0
